export const CHANGE_VALUE = "CHANGE_VALUE";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const INIT_RECORDS = "INIT_RECORDS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
